# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07554d433cc1ebb1d66c3f53887b5f9855d2bb7016af1e0817fdc08de729bb04723f9f99d4481a6107b5b5709d9735f660177ef1f9d3a58c8bbff0b9d39b559a

test:
  secret_key_base: 056c5cc6f76eafdf34a8c85daa8fd296e4e67f8d94cac3778c5d59900e560ed9a55a81a81076945777b29f2e81f5c5b97b549282092846cd4425a9a5ccff5715

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
